'use client';

import { AlertTriangle } from 'lucide-react';

export default function LegalDisclaimer() {
  return (
    <div className="w-full max-w-4xl mx-auto mt-8 bg-gray-50 border border-gray-300 rounded-lg p-4">
      <div className="flex items-start gap-3">
        <AlertTriangle className="w-5 h-5 text-gray-600 flex-shrink-0 mt-0.5" />
        <div>
          <h4 className="font-semibold text-gray-900 mb-1">Legal Disclaimer</h4>
          <p className="text-xs text-gray-700 leading-relaxed">
            This analysis is generated by AI and is for informational purposes only. It does not 
            constitute legal advice and should not be relied upon as a substitute for consultation 
            with a qualified attorney. ClauseGuard makes no warranties about the accuracy, 
            completeness, or reliability of the analysis. Always consult with a licensed attorney 
            for legal guidance specific to your situation.
          </p>
        </div>
      </div>
    </div>
  );
}
