import PDFDocument from 'pdfkit';
import { Writable } from 'stream';
import { RiskClause } from '../types';

export class PDFService {
  static async generateAnalysisReport(
    fileName: string,
    summary: string[],
    riskClauses: RiskClause[]
  ): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50 });
      const chunks: Buffer[] = [];

      const stream = new Writable({
        write(chunk, _encoding, callback) {
          chunks.push(chunk);
          callback();
        },
      });

      doc.pipe(stream);

      doc.fontSize(24).text('ClauseGuard Analysis Report', { align: 'center' });
      doc.moveDown();

      doc.fontSize(12).text(`Contract: ${fileName}`, { align: 'center' });
      doc.text(`Generated: ${new Date().toLocaleString()}`, { align: 'center' });
      doc.moveDown(2);

      doc.fontSize(16).text('Summary', { underline: true });
      doc.moveDown(0.5);

      summary.forEach((point, index) => {
        doc.fontSize(11).text(`${index + 1}. ${point}`, { indent: 20 });
        doc.moveDown(0.5);
      });

      doc.moveDown();

      doc.fontSize(16).text('Risk Analysis', { underline: true });
      doc.moveDown(0.5);

      if (riskClauses.length === 0) {
        doc.fontSize(11).text('No significant risks identified.', { indent: 20 });
      } else {
        riskClauses.forEach((clause, index) => {
          const riskColor = this.getRiskColor(clause.riskLevel);
          
          doc.fontSize(12).fillColor('black').text(`${index + 1}. `, { continued: true, indent: 20 });
          doc.fillColor(riskColor).text(`[${clause.riskLevel.toUpperCase()} RISK]`, { continued: false });
          
          if (clause.section) {
            doc.fontSize(10).fillColor('gray').text(`Section: ${clause.section}`, { indent: 30 });
          }
          
          doc.fontSize(10).fillColor('black').text(`Clause: "${clause.text}"`, { indent: 30 });
          doc.moveDown(0.3);
          doc.fontSize(10).text(`Risk: ${clause.explanation}`, { indent: 30 });
          doc.moveDown(1);
        });
      }

      doc.moveDown(2);
      doc.fontSize(8).fillColor('gray').text(
        'LEGAL DISCLAIMER: This report is generated by AI and is for informational purposes only. It does not constitute legal advice. Consult with a qualified attorney for legal guidance.',
        { align: 'center' }
      );

      doc.end();

      stream.on('finish', () => {
        resolve(Buffer.concat(chunks));
      });

      stream.on('error', reject);
    });
  }

  private static getRiskColor(riskLevel: string): string {
    switch (riskLevel) {
      case 'high':
        return '#DC2626';
      case 'medium':
        return '#F59E0B';
      case 'low':
        return '#10B981';
      default:
        return '#6B7280';
    }
  }
}
